# Generated by Django 5.1.2 on 2025-02-08 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hra_purchase_orders", "0001_initial"),
        ("hra_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="assigned_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hra_users",
                to="hra_users.user",
            ),
        ),
    ]
