# Generated by Django 5.1.2 on 2025-02-17 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hra_customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_service", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("quantity", models.IntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "verbose_name": "Invoice Item",
                "verbose_name_plural": "Invoice Items",
                "db_table": "invoice_item",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "invoice_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("invoice_number", models.IntegerField()),
                ("order_number", models.IntegerField()),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField()),
                ("terms", models.CharField(max_length=100)),
                ("invoice_month", models.CharField(max_length=20)),
                ("subject", models.CharField(max_length=255)),
                ("discount_type", models.CharField(max_length=50)),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("tax", models.DecimalField(decimal_places=2, max_digits=10)),
                ("terms_and_condition", models.TextField()),
                ("customer_notes", models.TextField()),
                (
                    "sub_total",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("invoice_status", models.CharField(max_length=50)),
                ("tenant_id", models.CharField(max_length=100)),
                (
                    "customer_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="hra_customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "db_table": "invoice",
            },
        ),
    ]
