# Generated by Django 5.1.2 on 2025-02-17 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hra_invoices", "0001_initial"),
        ("hra_purchase_orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_orders",
                to="hra_purchase_orders.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="hra_invoices.invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_items",
            field=models.ManyToManyField(
                related_name="invoices", to="hra_invoices.invoiceitem"
            ),
        ),
    ]
