# Generated by Django 5.1.2 on 2025-02-08 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hra_users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("education_type", models.CharField(max_length=100)),
                ("college", models.CharField(max_length=100)),
                ("year_of_passing", models.DateField()),
                ("major_specialization", models.CharField(max_length=100)),
                ("tenant_id", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hra_users.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Educations",
                "db_table": "education",
            },
        ),
    ]
