# Generated by Django 5.1.2 on 2025-02-18 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hra_education", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Education",
        ),
    ]
