# Generated by Django 5.1.2 on 2025-02-08 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hra_tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_street_address_1", models.CharField(max_length=100)),
                (
                    "current_street_address_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("current_country", models.CharField(max_length=100)),
                ("current_state", models.CharField(max_length=2)),
                ("current_city", models.CharField(max_length=100)),
                ("current_zip_code", models.CharField(max_length=10)),
                (
                    "permanent_street_address_1",
                    models.CharField(max_length=100),
                ),
                (
                    "permanent_street_address_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("permanent_country", models.CharField(max_length=100)),
                ("permanent_state", models.CharField(max_length=2)),
                ("permanent_city", models.CharField(max_length=100)),
                ("permanent_zip_code", models.CharField(max_length=10)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="hra_tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
