# Generated by Django 5.1.2 on 2025-02-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hra_address", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="permanent_city",
        ),
        migrations.RemoveField(
            model_name="address",
            name="permanent_country",
        ),
        migrations.RemoveField(
            model_name="address",
            name="permanent_state",
        ),
        migrations.RemoveField(
            model_name="address",
            name="permanent_street_address_1",
        ),
        migrations.RemoveField(
            model_name="address",
            name="permanent_street_address_2",
        ),
        migrations.RemoveField(
            model_name="address",
            name="permanent_zip_code",
        ),
    ]
