# Generated by Django 5.1.2 on 2025-02-18 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hra_users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_street_address_1", models.CharField(max_length=100)),
                (
                    "current_street_address_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("current_country", models.CharField(max_length=100)),
                ("current_state", models.CharField(max_length=20)),
                ("current_city", models.CharField(max_length=100)),
                ("current_zip_code", models.CharField(max_length=10)),
                (
                    "permanent_street_address_1",
                    models.CharField(max_length=100),
                ),
                (
                    "permanent_street_address_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "permanent_country",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "permanent_state",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "permanent_city",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "permanent_zip_code",
                    models.CharField(blank=True, max_length=10),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
