# Generated by Django 5.1.2 on 2025-02-18 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hra_users", "0002_addressdetail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addressdetail",
            name="user",
        ),
        migrations.AlterModelTable(
            name="addressdetail",
            table="address_model",
        ),
        migrations.CreateModel(
            name="EmpDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_role", models.CharField(max_length=20)),
                ("joining_date", models.DateTimeField()),
                ("dob", models.CharField(max_length=20)),
                ("status", models.CharField(default="1", max_length=20)),
                (
                    "reporting_manager",
                    models.ForeignKey(
                        db_column="reporting_manager",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_reporting_manager",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_user_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "emp_detail",
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("education", models.CharField(max_length=200)),
                ("board", models.CharField(max_length=250)),
                ("from_year", models.DateTimeField()),
                ("to_year", models.DateTimeField()),
                ("percentage", models.CharField(max_length=20)),
                ("school", models.CharField(max_length=200)),
                ("edu_type", models.CharField(max_length=100)),
                ("status", models.CharField(default="1", max_length=10)),
                (
                    "emp_id",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hra_users.empdetail",
                    ),
                ),
            ],
            options={
                "db_table": "education_model",
            },
        ),
        migrations.AddField(
            model_name="addressdetail",
            name="emp_id",
            field=models.ForeignKey(
                db_column="emp_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="hra_users.empdetail",
            ),
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True)),
                (
                    "salary_mode",
                    models.CharField(default="Hourly", max_length=20),
                ),
                ("hourly_rate", models.CharField(max_length=20)),
                ("skills", models.TextField()),
                ("status", models.CharField(default="1", max_length=10)),
                (
                    "emp_id",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hra_users.empdetail",
                    ),
                ),
            ],
            options={
                "db_table": "experience_model",
            },
        ),
        migrations.CreateModel(
            name="PersonalDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ssn_number", models.CharField(max_length=100)),
                ("home_phone", models.CharField(max_length=100)),
                ("personal_number", models.CharField(max_length=100)),
                ("emergency_contact", models.CharField(max_length=100)),
                ("status", models.CharField(default="1", max_length=10)),
                (
                    "emp_id",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hra_users.empdetail",
                    ),
                ),
            ],
            options={
                "db_table": "personal_detail",
            },
        ),
        migrations.CreateModel(
            name="Visadetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passport_number", models.CharField(max_length=100)),
                ("passport_country", models.CharField(max_length=100)),
                ("visa_type", models.CharField(max_length=100)),
                ("visa_start_date", models.DateTimeField()),
                ("visa_end_date", models.DateTimeField()),
                ("visa_country", models.CharField(max_length=100)),
                ("visa_renewal_date", models.DateTimeField()),
                ("visa_status", models.CharField(max_length=100)),
                ("status", models.CharField(default="1", max_length=10)),
                (
                    "emp_id",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hra_users.empdetail",
                    ),
                ),
            ],
            options={
                "db_table": "visa_detail",
            },
        ),
    ]
