# Generated by Django 5.1.2 on 2025-02-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hra_users", "0004_alter_user_job_role_role_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="status",
            field=models.CharField(default="1", max_length=10),
        ),
    ]
