# Generated by Django 5.1.2 on 2025-02-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hra_users", "0006_role_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empdetail",
            name="job_role",
        ),
        migrations.AddField(
            model_name="empdetail",
            name="emp_code",
            field=models.CharField(
                default="EMP001", max_length=20, unique=True
            ),
        ),
    ]
