# Generated by Django 5.1.2 on 2025-02-24 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hra_users", "0007_remove_empdetail_job_role_empdetail_emp_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("status", models.CharField(default="1", max_length=20)),
                ("table", models.CharField(default="1", max_length=200)),
                ("action", models.CharField(max_length=200)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_user_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "activity_logs",
            },
        ),
    ]
