# Generated by Django 5.1.2 on 2025-02-25 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hra_users", "0008_activitylogs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="1", max_length=20)),
                (
                    "emp_id",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_emp_id",
                        to="hra_users.empdetail",
                    ),
                ),
                (
                    "manager_id",
                    models.ForeignKey(
                        db_column="manager_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_manager_id",
                        to="hra_users.empdetail",
                    ),
                ),
            ],
            options={
                "db_table": "manager",
            },
        ),
    ]
