# Generated by Django 5.1.2 on 2025-02-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hra_users", "0010_reportingmanagers_delete_manager"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReportingManagers",
        ),
    ]
