# Generated by Django 5.1.2 on 2025-02-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hra_users", "0011_delete_reportingmanagers"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("comment", models.TextField()),
                ("status", models.CharField(default="1", max_length=10)),
            ],
            options={
                "db_table": "job_role",
            },
        ),
    ]
