# Generated by Django 5.1.2 on 2025-02-27 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hra_tenants', '0001_initial'),
        ('hra_users', '0012_jobrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('messaga', models.TextField()),
                ('notification_type', models.CharField(default='1', max_length=20)),
                ('status', models.CharField(default='1', max_length=20)),
                ('tenant_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tenant_id', to='hra_tenants.tenant')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
