# Generated by Django 5.1.2 on 2025-02-08 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hra_address", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customer_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
                ("billing_cycle", models.CharField(max_length=50)),
                ("payment_terms", models.CharField(max_length=50)),
                ("contact_person", models.CharField(max_length=100)),
                ("tenant_id", models.CharField(max_length=100)),
                (
                    "billing_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_address",
                        to="hra_address.address",
                    ),
                ),
                (
                    "shipping_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_address",
                        to="hra_address.address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "db_table": "customer",
            },
        ),
    ]
