# Generated by Django 5.1.2 on 2025-02-17 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hra_customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                (
                    "timesheet_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("week_month", models.CharField(max_length=20)),
                ("salary_mode", models.CharField(max_length=50)),
                ("hours", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "overtime_hours",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_salary",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("timesheet_status", models.CharField(max_length=50)),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="timesheet_attachments/",
                    ),
                ),
                (
                    "customer_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheets",
                        to="hra_customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timesheet",
                "verbose_name_plural": "Timesheets",
                "db_table": "timesheet",
            },
        ),
    ]
