# Generated by Django 5.1.2 on 2025-02-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hra_timesheets", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheet",
            name="image",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="status",
            field=models.CharField(default="1", max_length=20),
        ),
    ]
