# Generated by Django 5.1.2 on 2025-02-24 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hra_tenants", "0001_initial"),
        ("hra_timesheets", "0003_timesheet_image_timesheet_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheet",
            name="tenant_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_tenant_id",
                to="hra_tenants.tenant",
            ),
        ),
    ]
