# Generated by Django 5.1.2 on 2025-02-27 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hra_timesheets', '0004_timesheet_tenant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='timesheet_status',
        ),
        migrations.CreateModel(
            name='TimeSheetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('regular_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('status', models.CharField(default='1', max_length=20)),
                ('timesheet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_details', to='hra_timesheets.timesheet')),
            ],
            options={
                'verbose_name': 'Timesheet Detail',
                'verbose_name_plural': 'Timesheet Details',
                'db_table': 'timesheet_detail',
            },
        ),
    ]
