# Generated by Django 5.1.2 on 2025-02-27 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hra_purchase_orders', '0005_remove_assignpurchaseorder_tenant_id_and_more'),
        ('hra_timesheets', '0005_remove_timesheet_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='purchase_order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='hra_purchase_orders.purchaseorder'),
        ),
    ]
