# Generated by Django 5.1.2 on 2025-02-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hra_timesheets', '0006_remove_timesheet_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='timesheet_detail',
            field=models.TextField(default=''),
        ),
    ]
