# Generated by Django 5.1.2 on 2025-02-27 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hra_timesheets', '0007_timesheet_timesheet_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSheetDetails',
        ),
    ]
